version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  whatwhere:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: whatwhere
    stream: ext://sys.stdout
  file_handler:
      class: logging.FileHandler
      level: WARNING
      formatter: simple
      filename: info.log
      mode: w

loggers:
  productionlogger:
    handlers: [file_handler]
  root:
    handlers: [console]
